logging:
  config: classpath:config/logback.xml
  dir:  /mnt/logs/goods
jdbc:
  global:
    user: ${jdbc_user}
    password: ${jdbc_password} 
    poolsize: ${jdbc_poolsize}
    driverClassName: ${jdbc_driverclassName}
    minIdle: ${jdbc_minIdle}
    maxActive: ${jdbc_maxActive}
    maxWait: ${jdbc_maxWait}
    minEictableIdleTimeMillis: ${jdbc_minEictableIdleTimeMillis}
    defaultDatasource: goods
  jdbcConfigInfos:
    - name: goods
      url: ${jdbc_url}
      uniqueResourceName: mysql.goods.write
redis.pool:
  minIdle: 10
  maxIdle: 300
  maxWait: 1000
  testOnReturn: false
  testOnBorrow: false
  timeout: 1000
  maxActive: 300
  redisInfos:
    - name:default
      isdefault:true
      host:${redis_host}
      port:${redis_port}
      authKey:${redis_authKey}
      connectType:single
dubbo:
  registryAddress: ${dubbo.registry.address}
  application: goods
  port: 28894
upload:
   handler: ${upload.handler}
   path: ${upload.path}
   
kafka:
  bootstrapServers: ${kafka.address}
  kafkaDerail: ${kafka.kafkaDerail}
yzsysconfig:
  smsSwitch: ${sms.is.on}
  paymentCouponSwitch: ${payment.coupon.switch}
  zhiMiScale: ${yz.zhimi.scale}
  tempBucket: ${aliyun.oss.tempBucket}
  planSetting: ${discount.plan.setting}
  bucket: ${aliyun.oss.bucket}
  reptAmount: ${yz.rept.amount}
  addressMaxSize: ${address.max.size}
  signNumber: ${sign.base.number}
  fileBrowserUrl: ${file.browser.url}
  salesRemindTime: ${goods.sales.remind.time}
  submitState: ${submit.state}
  regCode: ${reg.code}
  invoicePhone: ${invoice.phone}
  invoiceType: ${invoice.type}
  recruitYear: ${yz.recruit.year}
  lotteryCode: ${lottery.code}