spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 30Mb
      max-request-size: 30Mb
server:
  display-name: bst
  port: 8182
logging:
  config: classpath:config/logback.xml
  dir:  /mnt/logs/bst
jdbc:
  global:
    user: ${jdbc_user}
    password: ${jdbc_password} 
    poolsize: ${jdbc_poolsize}
    driverClassName: ${jdbc_driverclassName}
    minIdle: ${jdbc_minIdle}
    maxActive: ${jdbc_maxActive}
    maxWait: ${jdbc_maxWait}
    minEictableIdleTimeMillis: ${jdbc_minEictableIdleTimeMillis}
    defaultDatasource: bms
  jdbcConfigInfos:
    - name: bms
      url: ${jdbc_url}
      uniqueResourceName: mysql.bms.write
redis.pool:
  minIdle: 10
  maxIdle: 300
  maxWait: 1000
  testOnReturn: false
  testOnBorrow: false
  timeout: 1000
  maxActive: 300
  redisInfos:
    - name:default
      isdefault:true
      host:${redis_host}
      port:${redis_port}
      authKey:${redis_authKey}
      connectType:single
oss:
  accessKeyId: LTAICtJ0nsZL33rZ
  accessKeySecret: iWfK0ZvQMEZQlddj23lF1iwz9O1eLH
  endpoint: oss-cn-shenzhen.aliyuncs.com
oss.file.browser: ${oss_file_browser}
dubbo:
  registryAddress: ${dubbo.registry.address}
  application: bst
upload:
   handler: ${upload.handler}
   path: ${upload.path}
yunsu : 
  username : yuanzhi
  password : yz2686013
  softid : 64700
  softkey : d36c1a3374dd4f08830aa764a41267ab
webservice:
  url: ${webservice.url}
cacheFile:
  dict: dict.json
  pcd: pcd.json
  sysParam: param.json
  mpJar: mpJar.json

yzsysconfig:
  paymentItemImaqAmount: ${payment.item.imaq.amount}

